[env:m5stack-core]
platform = espressif32@6.7.0
board = m5stack-core-esp32
framework = arduino
upload_speed = 1500000
monitor_speed = 115200
build_flags =
    -DCORE_DEBUG_LEVEL=5
    -DNFC_INTERFACE_I2C
    -DENABLE_HW_TESTS=0
    -I.
    -Icomponents/app/include
    -Icomponents/board/include
    -Icomponents/diagnostics/include
    -Icomponents/display/include
    -Icomponents/hx711/include
    -Icomponents/pn532/include
lib_deps =
    M5Unified=https://github.com/m5stack/M5Unified
    bogde/HX711
    adafruit/Adafruit PN532
    adafruit/Adafruit BusIO
